import React, { useRef, useState } from 'react';
import {
  AlertCircle,
  Camera,
  Check,
  CheckCircle2,
  ExternalLink,
  Globe,
  Image as ImageIcon,
  Loader2,
  Package,
  Plus,
  RefreshCw,
  Save,
  Sparkles,
  Trash2,
  Upload,
  X
} from 'lucide-react';
import { DEPARTMENTS } from '../data/departments';
import { DepartmentId, Product } from '../types';
import {
  enrichProductDetailsFromGoogle,
  fetchFurtherPicturesFromGoogle,
  generateGoogleDescription,
  getGoogleImagesSearchUrl,
  getGoogleWebSearchUrl,
  GoogleSearchResult
} from '../utils/googleSearchService';
import { GoogleSearchEnricher } from './GoogleSearchEnricher';
import {
  cleanAndResolveImageUrl,
  getProxiedImageUrl,
  DEFAULT_DEPT_IMAGES
} from '../utils/imageUrlResolver';

export const PACKAGING_PRESETS = [
  'Pieces',
  'Piece',
  'Box',
  'Dozen',
  'Kg',
  'Pack',
  'Bottle',
  'Strip',
  'Grams',
  'Liter',
  'Can',
  'Tub'
];

interface EditProductModalProps {
  product: Product;
  isOpen: boolean;
  onClose: () => void;
  onSave: (id: string, updates: Partial<Product>) => void;
}

export const EditProductModal: React.FC<EditProductModalProps> = ({
  product,
  isOpen,
  onClose,
  onSave
}) => {
  if (!isOpen) return null;

  // Basic Form states
  const [name, setName] = useState(product.name);
  const [department, setDepartment] = useState<DepartmentId>(product.department);
  const [category, setCategory] = useState(product.category);
  const [price, setPrice] = useState(product.price);
  const [originalPrice, setOriginalPrice] = useState<number | undefined>(product.originalPrice);
  const [stock, setStock] = useState(product.stock);
  const [unit, setUnit] = useState(product.unit);
  const [sku, setSku] = useState(product.sku);
  const [barcode, setBarcode] = useState(product.barcode || '');
  const [badge, setBadge] = useState(product.badge || '100% Genuine');
  const [inStock, setInStock] = useState(product.inStock);

  // Picture States
  const [image, setImage] = useState(product.image);
  const [additionalImages, setAdditionalImages] = useState<string[]>(product.additionalImages || []);
  const [googlePictures, setGooglePictures] = useState<string[]>([]);
  const [isFetchingPictures, setIsFetchingPictures] = useState(false);
  const [pictureSearchError, setPictureSearchError] = useState<string | null>(null);
  const [googleImageNotice, setGoogleImageNotice] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<'details' | 'pictures' | 'description'>('pictures');
  const fileInputRef = useRef<HTMLInputElement>(null);

  // Description & Formulation States (from Google search)
  const [description, setDescription] = useState(product.description);
  const [formulation, setFormulation] = useState(product.formulation || '');
  const [usage, setUsage] = useState(product.usage || '');
  const [dose, setDose] = useState(product.dose || '');
  const [productDetails, setProductDetails] = useState('');
  const [isGeneratingDesc, setIsGeneratingDesc] = useState(false);

  // Check if image is missing or default placeholder
  const isImagePlaceholder =
    !image ||
    image.includes('placeholder') ||
    image.includes('via.placeholder') ||
    image.trim() === '';

  // Auto-fetch further pictures from Google
  const handleFetchPicturesFromGoogle = async () => {
    setIsFetchingPictures(true);
    setPictureSearchError(null);
    try {
      const pictures = await fetchFurtherPicturesFromGoogle(name || product.name, department);
      if (pictures.length > 0) {
        setGooglePictures(pictures);
      } else {
        setPictureSearchError('No direct pictures found automatically. Use the direct Google Images link below to copy any picture.');
      }
    } catch (err: any) {
      setPictureSearchError(err.message || 'Error fetching pictures from Google.');
    } finally {
      setIsFetchingPictures(false);
    }
  };

  // Upload local picture from computer / mobile camera
  const handleLocalImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    if (file.size > 8 * 1024 * 1024) {
      alert('Picture file size must be less than 8MB.');
      return;
    }

    const reader = new FileReader();
    reader.onload = event => {
      const result = event.target?.result as string;
      if (result) {
        setImage(result);
      }
    };
    reader.readAsDataURL(file);
  };

  // Auto-generate / Rewrite description with Google (Formulation, Usage, Dose, Details)
  const handleAutoGenerateDescription = async () => {
    setIsGeneratingDesc(true);
    try {
      const enriched = await enrichProductDetailsFromGoogle(name || product.name, department);
      if (enriched.formulation) setFormulation(enriched.formulation);
      if (enriched.usage) setUsage(enriched.usage);
      if (enriched.dose) setDose(enriched.dose);
      if (enriched.productDetails) setProductDetails(enriched.productDetails);
      if (enriched.description) setDescription(enriched.description);

      // Auto-place Google picture if current image is placeholder or missing
      if (enriched.image && (isImagePlaceholder || !image)) {
        setImage(enriched.image);
        setGoogleImageNotice(`Auto-placed Google picture for "${name || product.name}" in stock window!`);
      }
      if (enriched.suggestedImages && enriched.suggestedImages.length > 0) {
        setGooglePictures(enriched.suggestedImages);
      }
    } catch (err) {
      console.error(err);
    } finally {
      setIsGeneratingDesc(false);
    }
  };

  // Function to re-compose structured description from individual fields
  const handleRecomposeDescription = () => {
    const sections: string[] = [];
    if (formulation.trim()) {
      sections.push(`【FORMULATION & COMPOSITION】\n${formulation.trim()}`);
    }
    if (productDetails.trim()) {
      sections.push(`【PRODUCT DETAILS & BENEFITS】\n${productDetails.trim()}`);
    }
    if (dose.trim()) {
      sections.push(`【DOSE & DOSAGE GUIDELINES】\n${dose.trim()}`);
    }
    if (usage.trim()) {
      sections.push(`【USAGE & STORAGE INSTRUCTIONS】\n${usage.trim()}`);
    }
    sections.push(`【JAN CHEMIST ORIGINAL GUARANTEE】\n100% Genuine original quality guaranteed ("With us its original"). Sourced directly from verified manufacturers and authorized pharmaceutical distributors with verified batch traceability.`);
    setDescription(sections.join('\n\n'));
  };

  // When Google auto-enrich returns a result
  const handleApplyGoogleResult = (result: GoogleSearchResult) => {
    setName(result.name);
    setDepartment(result.department);
    if (result.category) setCategory(result.category);
    if (result.price) setPrice(result.price);
    if (result.originalPrice) setOriginalPrice(result.originalPrice);
    if (result.unit) setUnit(result.unit);
    if (result.barcode) setBarcode(result.barcode);
    if (result.formulation) setFormulation(result.formulation);
    if (result.usage) setUsage(result.usage);
    if (result.dose) setDose(result.dose);
    if (result.productDetails) setProductDetails(result.productDetails);
    if (result.description) setDescription(result.description);
    if (result.image) setImage(result.image);
    if (result.suggestedImages && result.suggestedImages.length > 0) {
      setGooglePictures(result.suggestedImages);
    }
  };

  const handleAddSecondaryImage = (imgUrl: string) => {
    if (!additionalImages.includes(imgUrl) && imgUrl !== image) {
      setAdditionalImages([...additionalImages, imgUrl]);
    }
  };

  const handleRemoveSecondaryImage = (index: number) => {
    setAdditionalImages(additionalImages.filter((_, i) => i !== index));
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onSave(product.id, {
      name: name.trim(),
      department,
      category: category.trim(),
      price: Number(price),
      originalPrice: originalPrice ? Number(originalPrice) : undefined,
      stock: Number(stock),
      inStock: Number(stock) > 0 && inStock,
      unit: unit.trim(),
      sku: sku.trim(),
      barcode: barcode.trim() || undefined,
      image: image.trim(),
      additionalImages: additionalImages.length > 0 ? additionalImages : undefined,
      formulation: formulation.trim() || undefined,
      usage: usage.trim() || undefined,
      dose: dose.trim() || undefined,
      description: description.trim(),
      badge: badge.trim() || undefined
    });
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-3 sm:p-4">
      <div
        className="bg-white rounded-3xl max-w-3xl w-full shadow-2xl border border-slate-200 overflow-hidden animate-in fade-in"
        onClick={e => e.stopPropagation()}
      >
        {/* Modal Header */}
        <div className="p-4 sm:p-5 bg-gradient-to-r from-slate-900 via-indigo-950 to-purple-900 text-white flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-xl bg-purple-500/30 border border-purple-400/40 flex items-center justify-center text-purple-300">
              <Package className="w-4 h-4" />
            </div>
            <div>
              <h3 className="font-bold text-sm sm:text-base flex items-center gap-2">
                <span>Edit Inventory Picture, Description &amp; Details</span>
              </h3>
              <p className="text-[11px] text-purple-200 line-clamp-1">
                {product.name} ({product.sku})
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-1.5 text-white/80 hover:text-white rounded-lg hover:bg-white/10 transition cursor-pointer"
            title="Close modal"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Section Navigation Tabs */}
        <div className="flex items-center gap-2 px-4 sm:px-6 pt-3 pb-1 border-b border-slate-100 bg-slate-50/50">
          <button
            type="button"
            onClick={() => setActiveTab('pictures')}
            className={`py-2 px-3 rounded-xl font-bold text-xs flex items-center gap-1.5 transition cursor-pointer ${
              activeTab === 'pictures'
                ? 'bg-purple-700 text-white shadow-xs'
                : 'text-slate-600 hover:text-slate-900 hover:bg-slate-200/60'
            }`}
          >
            <ImageIcon className="w-4 h-4" />
            <span>Pictures &amp; Google Photos</span>
            {isImagePlaceholder && (
              <span className="w-2 h-2 rounded-full bg-amber-400 animate-ping"></span>
            )}
          </button>

          <button
            type="button"
            onClick={() => setActiveTab('description')}
            className={`py-2 px-3 rounded-xl font-bold text-xs flex items-center gap-1.5 transition cursor-pointer ${
              activeTab === 'description'
                ? 'bg-purple-700 text-white shadow-xs'
                : 'text-slate-600 hover:text-slate-900 hover:bg-slate-200/60'
            }`}
          >
            <Sparkles className="w-4 h-4" />
            <span>Description &amp; Specifications</span>
          </button>

          <button
            type="button"
            onClick={() => setActiveTab('details')}
            className={`py-2 px-3 rounded-xl font-bold text-xs flex items-center gap-1.5 transition cursor-pointer ${
              activeTab === 'details'
                ? 'bg-purple-700 text-white shadow-xs'
                : 'text-slate-600 hover:text-slate-900 hover:bg-slate-200/60'
            }`}
          >
            <Package className="w-4 h-4" />
            <span>Pricing, Stock &amp; Dept</span>
          </button>
        </div>

        {/* Modal Form */}
        <form onSubmit={handleSubmit} className="p-4 sm:p-6 space-y-4 text-xs max-h-[75vh] overflow-y-auto">
          {/* Missing Picture Alert Callout */}
          {isImagePlaceholder && (
            <div className="p-3 bg-amber-50 border border-amber-200 rounded-2xl flex flex-col sm:flex-row sm:items-center justify-between gap-2.5 text-xs text-amber-900 animate-in fade-in">
              <div className="flex items-center gap-2">
                <AlertCircle className="w-4 h-4 text-amber-600 shrink-0" />
                <span className="font-semibold">
                  Product picture is missing or generic. Would you like to upload one or search Google?
                </span>
              </div>
              <button
                type="button"
                onClick={handleFetchPicturesFromGoogle}
                disabled={isFetchingPictures}
                className="px-3 py-1.5 bg-amber-600 hover:bg-amber-700 text-white font-bold rounded-xl flex items-center justify-center gap-1.5 shadow-2xs transition cursor-pointer shrink-0"
              >
                {isFetchingPictures ? (
                  <Loader2 className="w-3.5 h-3.5 animate-spin" />
                ) : (
                  <Globe className="w-3.5 h-3.5" />
                )}
                <span>Fetch from Google Now</span>
              </button>
            </div>
          )}

          {/* TAB 1: PICTURES & GOOGLE IMAGES MANAGEMENT */}
          {activeTab === 'pictures' && (
            <div className="space-y-4">
              {/* Picture Action Bar */}
              <div className="flex flex-wrap items-center justify-between gap-2 p-3 bg-slate-50 border border-slate-200 rounded-2xl">
                <div>
                  <h4 className="font-bold text-slate-900 flex items-center gap-1.5">
                    <ImageIcon className="w-4 h-4 text-purple-700" />
                    <span>Product Visual Assets</span>
                  </h4>
                  <p className="text-[11px] text-slate-500">
                    Primary image displayed in catalog, plus secondary packaging and bottle views.
                  </p>
                </div>

                <div className="flex flex-wrap items-center gap-2">
                  {/* Google Images Direct Search Link */}
                  <a
                    href={getGoogleImagesSearchUrl(name || product.name)}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="px-3 py-1.5 bg-white hover:bg-emerald-50 text-emerald-700 border border-emerald-300 font-bold rounded-xl transition inline-flex items-center gap-1 shadow-2xs"
                    title="Search Google Images in a new tab"
                  >
                    <Globe className="w-3.5 h-3.5 text-emerald-600" />
                    <span>Search Google Images ↗</span>
                  </a>

                  {/* Device File Upload Button */}
                  <input
                    type="file"
                    ref={fileInputRef}
                    onChange={handleLocalImageUpload}
                    accept="image/*"
                    className="hidden"
                  />
                  <button
                    type="button"
                    onClick={() => fileInputRef.current?.click()}
                    className="px-3 py-1.5 bg-white hover:bg-slate-100 text-slate-800 border border-slate-300 font-bold rounded-xl transition cursor-pointer flex items-center gap-1 shadow-2xs"
                  >
                    <Upload className="w-3.5 h-3.5 text-slate-600" />
                    <span>Upload Picture File</span>
                  </button>

                  {/* Fetch Further Pictures from Google */}
                  <button
                    type="button"
                    onClick={handleFetchPicturesFromGoogle}
                    disabled={isFetchingPictures}
                    className="px-3.5 py-1.5 bg-purple-700 hover:bg-purple-800 text-white font-bold rounded-xl transition cursor-pointer flex items-center gap-1.5 shadow-sm disabled:opacity-50"
                  >
                    {isFetchingPictures ? (
                      <>
                        <Loader2 className="w-3.5 h-3.5 animate-spin" />
                        <span>Searching Google...</span>
                      </>
                    ) : (
                      <>
                        <Sparkles className="w-3.5 h-3.5 text-amber-300" />
                        <span>Search Google for Pictures</span>
                      </>
                    )}
                  </button>
                </div>
              </div>

              {/* Current Main Picture Preview & Input */}
              <div className="p-4 bg-white border border-slate-200 rounded-2xl shadow-xs space-y-3">
                <div className="font-bold text-slate-800 flex items-center justify-between">
                  <span>Current Main Picture:</span>
                  <span className="text-[10px] text-slate-400 font-normal">
                    This picture is shown in WhatsApp orders and product catalog
                  </span>
                </div>

                <div className="flex flex-col sm:flex-row items-center gap-4">
                  <div className="relative group shrink-0">
                    <img
                      src={cleanAndResolveImageUrl(image)}
                      alt={name}
                      referrerPolicy="no-referrer"
                      onError={e => {
                        const imgEl = e.target as HTMLImageElement;
                        if (!imgEl.src.includes('/api/image-proxy') && !imgEl.src.startsWith('data:')) {
                          imgEl.src = getProxiedImageUrl(image);
                        } else {
                          imgEl.src = DEFAULT_DEPT_IMAGES[department] || DEFAULT_DEPT_IMAGES.cosmetics;
                        }
                      }}
                      className="w-28 h-28 object-contain rounded-2xl border-2 border-purple-200 bg-slate-50 p-1 shadow-xs"
                    />
                    <div className="absolute bottom-1 right-1 bg-purple-900/80 text-white text-[9px] font-bold px-1.5 py-0.5 rounded-md">
                      Main Photo
                    </div>
                  </div>

                  <div className="flex-1 w-full space-y-2">
                    <div>
                      <div className="flex items-center justify-between mb-1">
                        <label className="text-[11px] font-bold text-slate-700">
                          Main Picture Direct URL:
                        </label>
                        <div className="flex items-center gap-1.5">
                          {image.includes('google.') && (
                            <button
                              type="button"
                              onClick={() => {
                                const cleaned = cleanAndResolveImageUrl(image);
                                setImage(cleaned);
                              }}
                              className="px-2 py-0.5 bg-blue-50 hover:bg-blue-100 text-blue-700 font-bold text-[10px] rounded border border-blue-200 cursor-pointer"
                              title="Extract direct image from Google redirect link"
                            >
                              ⚡ Clean Google URL
                            </button>
                          )}
                          <button
                            type="button"
                            onClick={() => {
                              setImage(getProxiedImageUrl(image));
                            }}
                            className="px-2 py-0.5 bg-purple-50 hover:bg-purple-100 text-purple-700 font-bold text-[10px] rounded border border-purple-200 cursor-pointer"
                            title="Route through local proxy to bypass CORS / Hotlink blocking"
                          >
                            🛡️ Route via Proxy
                          </button>
                        </div>
                      </div>
                      <input
                        type="text"
                        required
                        value={image}
                        onChange={e => {
                          const cleaned = cleanAndResolveImageUrl(e.target.value);
                          setImage(cleaned);
                        }}
                        placeholder="https://... direct image URL or paste from Google"
                        className="w-full px-3.5 py-2 border border-slate-300 rounded-xl focus:border-purple-600 focus:outline-none text-xs font-mono"
                      />
                    </div>
                    <div className="flex flex-wrap items-center justify-between gap-2 text-[11px] text-slate-500">
                      <span>✓ Automatically resolves Google Images links &amp; proxies hotlink-protected hosts.</span>
                      <span className="text-[10px] text-slate-400">Right-click &gt; &quot;Copy image address&quot; on Google</span>
                    </div>
                  </div>
                </div>

                {/* Quick Packaging (Box/Pieces/Dozen/Kg) & Price Editor */}
                <div className="pt-3 border-t border-slate-100 grid grid-cols-1 sm:grid-cols-2 gap-3">
                  <div>
                    <label className="block text-[11px] font-bold text-slate-800 mb-1">
                      Stock Packaging Unit (Box / Pieces / Dozen / Kg):
                    </label>
                    <div className="flex items-center gap-1.5 mb-1.5">
                      <input
                        type="text"
                        value={unit}
                        onChange={e => setUnit(e.target.value)}
                        placeholder="e.g. Box, Pieces, Dozen, Kg"
                        className="w-full px-3 py-1.5 border border-slate-300 rounded-xl focus:border-purple-600 focus:outline-none text-xs font-bold text-slate-800"
                      />
                    </div>
                    {/* Packaging preset quick-chips */}
                    <div className="flex flex-wrap items-center gap-1">
                      <span className="text-[10px] text-slate-400 font-semibold mr-0.5">Presets:</span>
                      {PACKAGING_PRESETS.map(preset => (
                        <button
                          key={preset}
                          type="button"
                          onClick={() => setUnit(preset)}
                          className={`px-2 py-0.5 rounded-lg text-[10px] font-bold border transition cursor-pointer ${
                            unit.toLowerCase() === preset.toLowerCase()
                              ? 'bg-purple-700 text-white border-purple-700 shadow-2xs'
                              : 'bg-slate-100 hover:bg-slate-200 text-slate-700 border-slate-200'
                          }`}
                        >
                          {preset}
                        </button>
                      ))}
                    </div>
                  </div>

                  <div>
                    <label className="block text-[11px] font-bold text-slate-800 mb-1">
                      Retail Price (PKR):
                    </label>
                    <div className="relative">
                      <span className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400 font-bold text-xs">
                        Rs.
                      </span>
                      <input
                        type="number"
                        min={1}
                        value={price}
                        onChange={e => setPrice(Number(e.target.value))}
                        className="w-full pl-9 pr-3 py-1.5 border border-slate-300 rounded-xl focus:border-purple-600 focus:outline-none text-xs font-bold text-emerald-800"
                      />
                    </div>
                    <div className="flex items-center justify-between text-[10px] text-slate-400 mt-1">
                      <span>Stock count: <strong>{stock}</strong></span>
                      <button
                        type="button"
                        onClick={() => setActiveTab('description')}
                        className="text-purple-700 font-bold hover:underline"
                      >
                        Edit Description &amp; Details &rarr;
                      </button>
                    </div>
                  </div>
                </div>
              </div>

              {/* Google Pictures Gallery (Discovered from Google) */}
              {googlePictures.length > 0 && (
                <div className="p-4 bg-gradient-to-br from-blue-50/60 to-purple-50/60 border border-blue-200 rounded-2xl space-y-3 animate-in fade-in">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <Globe className="w-4 h-4 text-blue-600" />
                      <span className="font-bold text-slate-900 text-xs sm:text-sm">
                        Pictures Discovered from Google for &ldquo;{name}&rdquo;
                      </span>
                    </div>
                    <span className="text-[10px] text-blue-700 font-semibold bg-blue-100 px-2 py-0.5 rounded-full">
                      {googlePictures.length} Pictures Found
                    </span>
                  </div>

                  <p className="text-[11px] text-slate-600">
                    Click any picture below to set it as your product’s main photo, or click &ldquo;+ Secondary&rdquo; to add it as an additional view:
                  </p>

                  <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                    {googlePictures.map((picUrl, idx) => {
                      const isMain = image === picUrl;
                      const isSecondary = additionalImages.includes(picUrl);

                      return (
                        <div
                          key={idx}
                          className={`relative rounded-xl overflow-hidden border-2 bg-white transition shadow-xs group ${
                            isMain
                              ? 'border-emerald-600 ring-2 ring-emerald-500/40'
                              : isSecondary
                              ? 'border-purple-500 ring-2 ring-purple-400/30'
                              : 'border-slate-200 hover:border-blue-400'
                          }`}
                        >
                          <img
                            src={picUrl}
                            alt={`Google result ${idx + 1}`}
                            className="w-full h-24 object-contain p-1 bg-slate-50 cursor-pointer"
                            onClick={() => setImage(picUrl)}
                          />

                          {/* Action Overlay */}
                          <div className="p-1.5 bg-white border-t border-slate-100 flex items-center justify-between text-[10px]">
                            <button
                              type="button"
                              onClick={() => setImage(picUrl)}
                              className={`px-1.5 py-0.5 rounded font-bold cursor-pointer transition ${
                                isMain
                                  ? 'bg-emerald-600 text-white'
                                  : 'text-slate-700 hover:text-emerald-700 hover:bg-emerald-50'
                              }`}
                            >
                              {isMain ? '✓ Main' : 'Set Main'}
                            </button>

                            <button
                              type="button"
                              onClick={() => handleAddSecondaryImage(picUrl)}
                              disabled={isMain || isSecondary}
                              className={`px-1.5 py-0.5 rounded font-semibold cursor-pointer transition ${
                                isSecondary
                                  ? 'bg-purple-100 text-purple-700'
                                  : 'text-slate-600 hover:text-purple-700 hover:bg-purple-50'
                              }`}
                            >
                              {isSecondary ? '✓ Extra' : '+ Extra'}
                            </button>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </div>
              )}

              {pictureSearchError && (
                <div className="p-3 bg-amber-50 border border-amber-200 rounded-xl text-xs text-amber-800 flex items-center gap-2">
                  <AlertCircle className="w-4 h-4 text-amber-600 shrink-0" />
                  <span>{pictureSearchError}</span>
                </div>
              )}

              {/* Secondary / Additional Pictures List */}
              {additionalImages.length > 0 && (
                <div className="p-4 bg-white border border-slate-200 rounded-2xl space-y-2.5">
                  <div className="font-bold text-slate-800 text-xs flex items-center justify-between">
                    <span>Additional Packaging &amp; Detail Pictures ({additionalImages.length}):</span>
                    <span className="text-[10px] text-slate-400">Available to customers in Quick View</span>
                  </div>

                  <div className="flex flex-wrap items-center gap-3">
                    {additionalImages.map((extraImg, idx) => (
                      <div
                        key={idx}
                        className="relative group w-20 h-20 rounded-xl overflow-hidden border border-slate-300 bg-slate-50"
                      >
                        <img
                          src={extraImg}
                          alt={`Additional ${idx + 1}`}
                          className="w-full h-full object-contain p-1"
                        />
                        <button
                          type="button"
                          onClick={() => handleRemoveSecondaryImage(idx)}
                          className="absolute top-1 right-1 p-1 bg-red-600 text-white rounded-md opacity-80 hover:opacity-100 transition cursor-pointer"
                          title="Remove this extra picture"
                        >
                          <Trash2 className="w-3 h-3" />
                        </button>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}

          {/* TAB 2: DESCRIPTION & CLINICAL SPECIFICATIONS MANAGEMENT */}
          {activeTab === 'description' && (
            <div className="space-y-4">
              {/* Google Image Notice Banner if picture was fetched/placed */}
              {googleImageNotice && (
                <div className="p-3 bg-emerald-50 border border-emerald-300 rounded-2xl flex items-center justify-between gap-3 text-xs text-emerald-900 animate-in fade-in">
                  <div className="flex items-center gap-2">
                    <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
                    <span>{googleImageNotice}</span>
                  </div>
                  <button
                    type="button"
                    onClick={() => setActiveTab('pictures')}
                    className="px-2.5 py-1 bg-emerald-700 hover:bg-emerald-800 text-white font-bold text-[11px] rounded-lg cursor-pointer"
                  >
                    View in Pictures
                  </button>
                </div>
              )}

              <div className="p-4 bg-white border border-slate-200 rounded-2xl shadow-xs space-y-4">
                <div className="flex flex-wrap items-center justify-between gap-2 pb-3 border-b border-slate-100">
                  <div>
                    <h4 className="font-bold text-slate-900 text-xs sm:text-sm flex items-center gap-1.5">
                      <Sparkles className="w-4 h-4 text-purple-600" />
                      <span>Google Product Grounding: Formulation, Usage, Dose &amp; Details</span>
                    </h4>
                    <p className="text-[11px] text-slate-500">
                      Fetches authentic specifications from Google and structures them for your catalog &amp; WhatsApp orders.
                    </p>
                  </div>

                  {/* Auto-Generate / Polish Description from Google */}
                  <button
                    type="button"
                    onClick={handleAutoGenerateDescription}
                    disabled={isGeneratingDesc}
                    className="px-4 py-2 bg-gradient-to-r from-purple-700 via-indigo-700 to-purple-800 hover:from-purple-800 hover:to-indigo-800 text-white font-bold text-xs rounded-xl transition cursor-pointer flex items-center gap-1.5 shadow-sm disabled:opacity-50"
                    title="Retrieve formulation, dosage, usage, product details & Google images"
                  >
                    {isGeneratingDesc ? (
                      <>
                        <Loader2 className="w-4 h-4 animate-spin" />
                        <span>Searching Google &amp; Rewriting...</span>
                      </>
                    ) : (
                      <>
                        <Sparkles className="w-4 h-4 text-amber-300" />
                        <span>Get from Google &amp; Rewrite</span>
                      </>
                    )}
                  </button>
                </div>

                {/* 4 Structured Information Fields */}
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3.5">
                  {/* 1. Formulation & Composition */}
                  <div className="space-y-1">
                    <label className="block text-[11px] font-bold text-slate-800 flex items-center gap-1">
                      <span>🧪 Formulation &amp; Active Ingredients</span>
                    </label>
                    <textarea
                      rows={2}
                      value={formulation}
                      onChange={e => setFormulation(e.target.value)}
                      placeholder="e.g. Paracetamol 500mg, Caffeine 65mg / 10% Niacinamide + 1% Zinc PCA..."
                      className="w-full p-2.5 border border-slate-300 rounded-xl focus:border-purple-600 focus:outline-none text-xs text-slate-800"
                    />
                  </div>

                  {/* 2. Dose & Dosage Guidelines */}
                  <div className="space-y-1">
                    <label className="block text-[11px] font-bold text-slate-800 flex items-center gap-1">
                      <span>💊 Dose &amp; Dosage Guidelines</span>
                    </label>
                    <textarea
                      rows={2}
                      value={dose}
                      onChange={e => setDose(e.target.value)}
                      placeholder="e.g. 1-2 tablets every 4 to 6 hours as needed. Max 8 tablets in 24 hours..."
                      className="w-full p-2.5 border border-slate-300 rounded-xl focus:border-purple-600 focus:outline-none text-xs text-slate-800"
                    />
                  </div>

                  {/* 3. Usage & Storage Directions */}
                  <div className="space-y-1">
                    <label className="block text-[11px] font-bold text-slate-800 flex items-center gap-1">
                      <span>🌿 Usage Directions &amp; Storage</span>
                    </label>
                    <textarea
                      rows={2}
                      value={usage}
                      onChange={e => setUsage(e.target.value)}
                      placeholder="e.g. Take with water after meals. Store in a dry place below 30°C away from heat..."
                      className="w-full p-2.5 border border-slate-300 rounded-xl focus:border-purple-600 focus:outline-none text-xs text-slate-800"
                    />
                  </div>

                  {/* 4. Product Details & Origin */}
                  <div className="space-y-1">
                    <label className="block text-[11px] font-bold text-slate-800 flex items-center gap-1">
                      <span>📋 Product Details &amp; Authenticity</span>
                    </label>
                    <textarea
                      rows={2}
                      value={productDetails}
                      onChange={e => setProductDetails(e.target.value)}
                      placeholder="e.g. Authorized distributor stock in Pakistan. For headache, fever, and general body ache..."
                      className="w-full p-2.5 border border-slate-300 rounded-xl focus:border-purple-600 focus:outline-none text-xs text-slate-800"
                    />
                  </div>
                </div>

                {/* Re-compose button */}
                <div className="flex items-center justify-between pt-1">
                  <span className="text-[11px] text-slate-500 font-medium">
                    Adjust the 4 sections above or write custom text below:
                  </span>
                  <button
                    type="button"
                    onClick={handleRecomposeDescription}
                    className="px-3 py-1.5 bg-slate-100 hover:bg-purple-100 text-purple-800 font-bold text-xs rounded-xl border border-slate-200 transition cursor-pointer flex items-center gap-1"
                  >
                    <RefreshCw className="w-3.5 h-3.5" />
                    <span>Re-assemble Full Description</span>
                  </button>
                </div>

                {/* Full Structured Description (Storefront View) */}
                <div className="space-y-1.5 pt-2 border-t border-slate-100">
                  <label className="block text-xs font-bold text-slate-800">
                    Complete Structured Description (Storefront &amp; Customer View)
                  </label>
                  <textarea
                    rows={6}
                    value={description}
                    onChange={e => setDescription(e.target.value)}
                    placeholder="Provide full description, benefits, ingredients, usage directions, and Jan Chemist authenticity statements..."
                    className="w-full p-3.5 border border-slate-300 rounded-xl focus:border-purple-600 focus:outline-none text-xs leading-relaxed font-sans text-slate-800 shadow-2xs"
                  />
                  <div className="flex items-center justify-between text-[11px] text-slate-400 mt-1">
                    <span>Characters: {description.length}</span>
                    <span>Supports multi-line formatting</span>
                  </div>
                </div>

                {/* Quick Add Sentence Shortcuts */}
                <div className="space-y-1.5 pt-1">
                  <div className="text-[11px] font-bold text-slate-700">Quick Insert Shortcuts:</div>
                  <div className="flex flex-wrap items-center gap-1.5">
                    <button
                      type="button"
                      onClick={() =>
                        setDescription(
                          prev => `${prev.trim()}\n\n• 100% Genuine original quality guaranteed at Jan Chemist ("With us its original").`
                        )
                      }
                      className="px-2 py-1 rounded-lg bg-slate-100 hover:bg-purple-100 text-slate-700 hover:text-purple-800 text-[10px] font-semibold border border-slate-200 transition cursor-pointer"
                    >
                      + &quot;100% Original Guarantee&quot;
                    </button>

                    <button
                      type="button"
                      onClick={() =>
                        setDescription(
                          prev => `${prev.trim()}\n\n• Sourced directly from official manufacturers and authorized distributors.`
                        )
                      }
                      className="px-2 py-1 rounded-lg bg-slate-100 hover:bg-purple-100 text-slate-700 hover:text-purple-800 text-[10px] font-semibold border border-slate-200 transition cursor-pointer"
                    >
                      + &quot;Official Distributor Source&quot;
                    </button>

                    <button
                      type="button"
                      onClick={() =>
                        setDescription(
                          prev => `${prev.trim()}\n\n• Storage: Store in a cool, dry place below 30°C away from direct sunlight.`
                        )
                      }
                      className="px-2 py-1 rounded-lg bg-slate-100 hover:bg-purple-100 text-slate-700 hover:text-purple-800 text-[10px] font-semibold border border-slate-200 transition cursor-pointer"
                    >
                      + &quot;Storage Directions&quot;
                    </button>

                    <button
                      type="button"
                      onClick={() =>
                        setDescription(
                          prev => `${prev.trim()}\n\n• Batch and expiry date verified by on-duty pharmacist.`
                        )
                      }
                      className="px-2 py-1 rounded-lg bg-slate-100 hover:bg-purple-100 text-slate-700 hover:text-purple-800 text-[10px] font-semibold border border-slate-200 transition cursor-pointer"
                    >
                      + &quot;Pharmacist Batch Verification&quot;
                    </button>
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* TAB 3: PRODUCT BASIC DETAILS, PRICING & STOCK */}
          {activeTab === 'details' && (
            <div className="space-y-4">
              {/* Google Auto-Enricher Bar */}
              <GoogleSearchEnricher
                initialQuery={name || product.name}
                preferredDept={department}
                currentImageUrl={image}
                onApplyResult={handleApplyGoogleResult}
                onSelectImage={newImgUrl => setImage(newImgUrl)}
              />

              <div className="p-4 bg-white border border-slate-200 rounded-2xl shadow-xs space-y-3">
                <div>
                  <label className="block font-bold text-slate-800 mb-1">Product Title *</label>
                  <input
                    type="text"
                    required
                    value={name}
                    onChange={e => setName(e.target.value)}
                    placeholder="Product name, brand, dosage/size..."
                    className="w-full px-3.5 py-2 border border-slate-300 rounded-xl focus:border-purple-600 focus:outline-none text-xs font-semibold text-slate-900"
                  />
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  <div>
                    <label className="block font-bold text-slate-800 mb-1">Department *</label>
                    <select
                      value={department}
                      onChange={e => setDepartment(e.target.value as any)}
                      className="w-full px-3 py-2 border border-slate-300 rounded-xl focus:border-purple-600 focus:outline-none capitalize font-semibold bg-white text-slate-800"
                    >
                      {DEPARTMENTS.map(d => (
                        <option key={d.id} value={d.id}>
                          {d.name}
                        </option>
                      ))}
                    </select>
                  </div>

                  <div>
                    <label className="block font-bold text-slate-800 mb-1">Category / Subcategory</label>
                    <input
                      type="text"
                      value={category}
                      onChange={e => setCategory(e.target.value)}
                      placeholder="e.g. Pain Relief, Shampoos, Lipsticks"
                      className="w-full px-3.5 py-2 border border-slate-300 rounded-xl focus:border-purple-600 focus:outline-none text-xs"
                    />
                  </div>
                </div>

                {/* Price & Stock Row */}
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                  <div>
                    <label className="block font-bold text-slate-800 mb-1">Price (PKR) *</label>
                    <div className="relative">
                      <span className="absolute left-2.5 top-1/2 -translate-y-1/2 text-slate-400 font-bold text-[11px]">
                        Rs.
                      </span>
                      <input
                        type="number"
                        required
                        min={1}
                        value={price}
                        onChange={e => setPrice(Number(e.target.value))}
                        className="w-full pl-8 pr-3 py-2 border border-slate-300 rounded-xl focus:border-purple-600 focus:outline-none font-bold text-emerald-800 text-xs"
                      />
                    </div>
                  </div>

                  <div>
                    <label className="block font-bold text-slate-800 mb-1">Original Price (Strike)</label>
                    <div className="relative">
                      <span className="absolute left-2.5 top-1/2 -translate-y-1/2 text-slate-400 font-bold text-[11px]">
                        Rs.
                      </span>
                      <input
                        type="number"
                        placeholder="Optional"
                        value={originalPrice || ''}
                        onChange={e => setOriginalPrice(e.target.value ? Number(e.target.value) : undefined)}
                        className="w-full pl-8 pr-3 py-2 border border-slate-300 rounded-xl focus:border-purple-600 focus:outline-none text-xs"
                      />
                    </div>
                  </div>

                  <div>
                    <label className="block font-bold text-slate-800 mb-1">Stock Quantity *</label>
                    <input
                      type="number"
                      required
                      min={0}
                      value={stock}
                      onChange={e => setStock(Number(e.target.value))}
                      className="w-full px-3 py-2 border border-slate-300 rounded-xl focus:border-purple-600 focus:outline-none font-bold text-xs"
                    />
                  </div>

                  <div className="col-span-2 sm:col-span-1">
                    <label className="block font-bold text-slate-800 mb-1">
                      Packaging Unit (Box / Pieces / Dozen / Kg) *
                    </label>
                    <input
                      type="text"
                      required
                      value={unit}
                      onChange={e => setUnit(e.target.value)}
                      placeholder="e.g. Box, Pieces, Dozen, Kg"
                      className="w-full px-3 py-2 border border-slate-300 rounded-xl focus:border-purple-600 focus:outline-none text-xs font-semibold"
                    />
                    <div className="flex flex-wrap items-center gap-1 mt-1.5">
                      {PACKAGING_PRESETS.slice(0, 6).map(preset => (
                        <button
                          key={preset}
                          type="button"
                          onClick={() => setUnit(preset)}
                          className={`px-1.5 py-0.5 rounded text-[10px] font-bold border transition cursor-pointer ${
                            unit.toLowerCase() === preset.toLowerCase()
                              ? 'bg-purple-700 text-white border-purple-700'
                              : 'bg-slate-100 hover:bg-slate-200 text-slate-700 border-slate-200'
                          }`}
                        >
                          {preset}
                        </button>
                      ))}
                    </div>
                  </div>
                </div>

                {/* SKU, Barcode, Badge */}
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                  <div>
                    <label className="block font-bold text-slate-800 mb-1">SKU Code</label>
                    <input
                      type="text"
                      value={sku}
                      onChange={e => setSku(e.target.value)}
                      className="w-full px-3 py-2 border border-slate-300 rounded-xl focus:border-purple-600 focus:outline-none font-mono text-xs font-semibold"
                    />
                  </div>

                  <div>
                    <label className="block font-bold text-slate-800 mb-1">Barcode (EAN/UPC)</label>
                    <input
                      type="text"
                      placeholder="Barcode from packaging"
                      value={barcode}
                      onChange={e => setBarcode(e.target.value)}
                      className="w-full px-3 py-2 border border-slate-300 rounded-xl focus:border-purple-600 focus:outline-none font-mono text-xs"
                    />
                  </div>

                  <div>
                    <label className="block font-bold text-slate-800 mb-1">Quality Badge</label>
                    <input
                      type="text"
                      placeholder="100% Genuine, Best Seller"
                      value={badge}
                      onChange={e => setBadge(e.target.value)}
                      className="w-full px-3 py-2 border border-slate-300 rounded-xl focus:border-purple-600 focus:outline-none text-xs"
                    />
                  </div>
                </div>

                {/* In-Stock Toggle */}
                <div className="flex items-center justify-between p-3 bg-slate-50 rounded-xl border border-slate-200">
                  <div>
                    <span className="font-bold text-slate-800 block text-xs">Customer Availability</span>
                    <span className="text-[11px] text-slate-500">
                      When enabled, customers can view and add this item to their WhatsApp cart.
                    </span>
                  </div>
                  <button
                    type="button"
                    onClick={() => setInStock(!inStock)}
                    className={`px-3 py-1.5 rounded-full text-xs font-bold transition cursor-pointer ${
                      inStock ? 'bg-emerald-100 text-emerald-800' : 'bg-red-100 text-red-800'
                    }`}
                  >
                    {inStock ? 'Active in Store' : 'Hidden / Disabled'}
                  </button>
                </div>
              </div>
            </div>
          )}

          {/* Modal Actions */}
          <div className="pt-3 border-t border-slate-200 flex items-center justify-between">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 text-slate-600 hover:text-slate-800 hover:bg-slate-100 rounded-xl font-semibold transition cursor-pointer"
            >
              Cancel
            </button>

            <button
              type="submit"
              className="px-6 py-2.5 bg-gradient-to-r from-purple-700 to-indigo-700 hover:from-purple-800 hover:to-indigo-800 text-white font-bold rounded-xl shadow-md transition cursor-pointer flex items-center gap-1.5"
            >
              <Save className="w-4 h-4" />
              <span>Save Picture &amp; Details</span>
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};
